config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  mount SeShop::Engine, at: "/menu"
  root 'home#index'
  get '/logout' => 'user#logout', as: :logout
  get '/DonerStreet' => 'home#doner', as: 'donerstreet'
  get '/Cinnamon' => 'home#cinnamon', as: 'cinnamon'
  get '/contacts' => 'contacts#index', as: 'contacts'
  get '/pay_info' => 'contacts#pay_info', as: 'pay_info'

  %w( 404 422 500 ).each do |code|
    get code, :to => "errors#show", :code => code
  end
  resource :shop, path: "shop/:shop_id/", only:[] do
    resources :photos, except: [:update, :edit]
  end
  patch 'photos/update' => 'photos#update', as: 'photos_update'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :set_uuid, only: [:index]
  before_action :set_orders, only: [:index]
  before_action :set_main_shop, only: [:index, :doner, :cinnamon]
  def index
    @main_shop = SeShop::Shop.friendly.find('daily-diner')
    if @main_shop.se_shop_categories.where('tomain = ?', true)
      @categories =@main_shop.se_shop_categories.where('tomain = ?', true).first
      if @categories.present? && @categories.se_shop_items.present?
        @items = @categories.se_shop_items.limit(12)
      end

    end
    if SeShop::Shop.any?
      @shops = SeShop::Shop.all
    end

  end

  def doner
    @shop = SeShop::Shop.friendly.find('doner-street')
  end

  def cinnamon
    @shop = SeShop::Shop.friendly.find('kofe-bar-koritsa')
  end


  private
  def set_orders
    @orders = SeShop::Order.where('user_uuid = ? AND order_status_id = ?', @uuid, 1)
  end
  def set_uuid
    if cookies[:uuid].blank?
      cookies[:uuid] = SecureRandom.uuid
    end
    @uuid = cookies[:uuid]
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_filials.html.haml
.filials
  .emblemBlock.flex
    - @shops.each do |shop|
      %a.no-link(href= '#{se_shop.shop_path(shop)}')
        %img{:src => shop.logo}
  -if @main_shop.motto
    .motto= @main_shop.motto
  .lineSeparator.flex
    %img{:src => asset_url('line.png')}

app/views/home/_menucontainer.html.haml
.menuContainer
  .menuTitle Меню
  -if !@shop.phone.blank?
    .contact-phone Телефон для заказа #{@shop.phone}
  .homeItems-wrapper
    -if @shop.se_shop_categories
      -@shop.se_shop_categories.each do |category|
        -@citems =  category.se_shop_items
        -@csubcat = category.se_shop_subcategories
        -if (@citems && @citems.any?) || (@csubcat && @csubcat.any?)
          -if @citems && @citems.any?
            %h2.cat-name= category.name
            .itemsGrid.flex
              =render partial: 'se_shop/layouts/items', locals: {shop: @shop, counter: false}, collection: @citems, as: :item
          -elsif @csubcat
            -@csubcat.each do |subcategory|
              - @items = subcategory.se_shop_items
              -if @items && @items.any?
                %h2.cat-name= subcategory.name
                .itemsGrid.flex{:data => {target:"#{subcategory.name}"}}
                  =render partial: 'se_shop/layouts/items', locals: {shop: @shop  , counter: false}, collection: @items, as: :item

app/views/home/cinnamon.html.haml
- provide(:title, "#{@shop.name}")
- provide(:bg, asset_path('bg2.png'))
.headerPhotos.flex.fixHeight
  .photo-head
    - @photos_block =  set_photos_block(@shop)
    -if @photos_block
      - @photos_block.each_with_index  do |photo, index|
        -if index < 4
          .photo-box.setSize.showPhoto(data-bg="#{photo.image_url}" data-size="3")
        -else
          .photo-box.setSize(data-bg="#{photo.image_url}" data-size="3")
  =link_to "Редактировать фото", shop_photos_path(@shop), class: "link-to-edit-header" if user_admin?
.filials
  .emblemBlock
    .lenta
      .flex
        %a.no-link{:href => root_path}
          %img{:src => asset_path("diner.png"), :style => "width: 180px"}
        %a.no-link.cinnamon.active{:href => "#"}
          %img{:src => asset_path("cinnamon.png"), :style => "width: 219px"}
        %a.no-link{:href => donerstreet_path}
          %img{:src => asset_path("street.png"), :style => "width: 120px"}
  -if !@shop.motto.blank?
    .motto= raw @shop.motto
  .lineSeparator.flex
    %img{:src => asset_url('line.png')}

.menuContainer
  -if !@shop.phone.blank?
    .contact-phone Телефон для заказа #{@shop.phone}
//= render partial: 'menucontainer'

.modal-window
  .close-button
    %i.fa.fa-times
  .item-open
.modal-overlay

app/views/home/doner.html.haml
- provide(:title, "#{@shop.name}")
- provide(:bg, asset_path('bg1.png'))
.headerPhotos.flex.fixHeight
  .photo-head
    - @photos_block =  set_photos_block(@shop)
    -if @photos_block
      - @photos_block.each_with_index  do |photo, index|
        -if index < 4
          .photo-box.setSize.showPhoto(data-bg="#{photo.image_url}" data-size="3")
        -else
          .photo-box.setSize(data-bg="#{photo.image_url}" data-size="3")
  =link_to "Редактировать фото", shop_photos_path(@shop), class: "link-to-edit-header" if user_admin?
.filials
  .emblemBlock
    .lenta
      .flex
        %a.no-link.cinnamon{:href => cinnamon_path}
          %img{:src => asset_path("cinnamon.png"), :style => "width: 219px"}
        %a.no-link.active{:href => "#"}
          %img{:src => asset_path("street.png"), :style => "width: 120px"}
        %a.no-link{:href => root_path}
          %img{:src => asset_path("diner.png"), :style => "width: 180px"}
  -if !@shop.motto.blank?
    .motto= raw @shop.motto
  .lineSeparator.flex
    %img{:src => asset_url('line.png')}

.menuContainer
  -if !@shop.phone.blank?
    .contact-phone Телефон для заказа #{@shop.phone}
  .homeItems-wrapper
//= render partial: 'menucontainer'


.modal-window
  .close-button
    %i.fa.fa-times
  .item-open
.modal-overlay

app/views/home/index.html.haml
- provide(:title, "Daily Diner")
- @photos_block = set_photos_block(@main_shop)
.headerPhotos.flex
  .photo-head
    -if @photos_block
      - @photos_block.each_with_index  do |photo, index|
        -if index < 4
          .photo-box.setSize.showPhoto(data-bg="#{photo.image_url}" data-size="3")
        -else
          .photo-box.setSize(data-bg="#{photo.image_url}" data-size="3")
  =link_to "Редактировать фото", shop_photos_path(@main_shop), class: "link-to-edit-header" if user_admin?
.filials.before-pattern
  .emblemBlock
    .lenta
      .flex
        %a.no-link.cinnamon{:href => cinnamon_path}
          %img{:src => asset_path("cinnamon.png"), :style => "width: 219px"}
        %a.no-link.active{:href => "#"}
          %img{:src => asset_path("diner.png"), :style => "width: 180px"}
        %a.no-link{:href => donerstreet_path}
          %img{:src => asset_path("street.png"), :style => "width: 120px"}
  -if @main_shop.motto
    .motto= raw @main_shop.motto
  .lineSeparator.flex
    %img{:src => asset_url('line.png')}
-if @categories && @categories.se_shop_items.limit(6).any?
  .menuContainer
    .bTitle.flex
      = link_to "Всё меню", se_shop.shop_path(@main_shop), :class => "no-link linkButton"
    .homeItems-wrapper.itemsGrid.flex
      - @shop = @main_shop
      = render partial: 'se_shop/layouts/items', locals: {counter: true}, collection: @items, as: :item
    .fullMenuLink.flex
      = link_to "Всё меню", se_shop.shop_path(@main_shop), :class => "no-link linkButton"

  .cart-link.stop
    .item-amount
      %span= @orders.length
    %i.fa.fa-shopping-cart
  .modal-window
    .close-button
      %i.fa.fa-times
    =render 'se_shop/order/cart', orders: @orders
  .modal-window
    .close-button
      %i.fa.fa-times
    .item-open
  .modal-overlay